#cloud-config
hostname: $hostname
coreos:
  etcd2:
    heartbeat-interval: 600
    election-timeout: 6000
  fleet:
    metadata: name=%H,controlPlane=true,dataPlane=true,routerMesh=true
    engine-reconcile-interval: 10
    etcd-request-timeout: 5
    agent-ttl: 120s
  units:
  - name: 00-eth0.network
    runtime: true
    content: |
      [Match]
      Name=eth0

      [Network]
      DHCP=ipv4
      Address=$public_ipv4/24
      Address=$private_ipv4/17
      Gateway=$gateway.1
      DNS=72.14.179.5
      DNS=8.8.8.8
      DNS=208.67.222.222
      Domains=linode-dallas.dns.myriadmobile.com myriadmobile.com

      [DHCP]
      UseDNS=false
      CriticalConnection=true
  - name: disable-ipv6.service
    command: start
    content: |
      [Unit]
      Description=Disable IPv6. The notion of a security group does not exist on Linode. To make firewalling each Linode easier, disable IPv6.
      Before=network.target

      [Service]
      Type=oneshot
      ExecStart=/bin/sh -c "sysctl -w net.ipv6.conf.all.disable_ipv6=1"
write_files:
  - path: /etc/environment
    content: |
      COREOS_PUBLIC_IPV4=$public_ipv4
      COREOS_PRIVATE_IPV4=$private_ipv4
